#!/bin/bash

# This file is sourced when Bash is run in an interactive shell. It holds
# functions, aliases, etc. that are specific to interactive shell usage.

# ::::::::: CDPATH :::::::::::::::::::::::::::
{
  # DON'T EXPORT CDPATH, it can screw up scripts.
  CDPATH=".:~/Development:~/Development/resources:~"
}

# ::::::::: Colors :::::::::::::::::::::::::::
{
  [ -f ~/.ansi_colors ] && . ~/.ansi_colors

  if [[ -n "${THEME:-x}" ]]; then
    theme=$(grep -oP '(?<=^colors: \*)[[:word:]]+' ~/.config/alacritty/alacritty.yml)
    export THEME=${theme:-dark}
  fi

  export LESS="-~"
  export MANPAGER="less -isR"

  export LESS_TERMCAP_md=$'\e[1;37m'
  export LESS_TERMCAP_me=$'\e[0m'

  export LESS_TERMCAP_us=$'\e[0;36m' # cyan
  export LESS_TERMCAP_ue=$'\e[0m'

  export GROFF_NO_SGR=1
}

# ::::::::: Prompt :::::::::::::::::::::::::::
{
  if [ "$TERM" != "dumb" -o -n "$INSIDE_EMACS" ]; then
    GREEN="\033[0;32m"
    BLACK="\033[0;30m"
    BOLD="\033[1m"
    NORMAL="\033[0m"

    PS1="\n╭\[${BOLD}\]\w\[${NORMAL}\]\$(_git_ps1_)\[${NORMAL}\] \[${BLACK}\]\t\[${NORMAL}\]\n╰(\u)• "
    PS2=" ❯ "
    PS4=" + "

    _git_ps1_() {
      local color="${GREEN}"

      # __git_ps1 inserts the current git branch where %s is
      echo "$(__git_ps1 " (${color}%s${NORMAL})")"
    }

    if test "$TERM" = "xterm"; then
      PS1="\[\033]2;\h:\u:\w\007\]${PS1}"
    fi
  fi
}

# ::::::::: Sources ::::::::::::::::::::::::::
{
  files=(~/.bashrc.local
         ~/.bash_aliases
         ~/.bash_functions)

  for file in "${files[@]}"; do
    [ -r "$file" ] && . "$file"
  done
}

# ::::::::: Shell Options ::::::::::::::::::::
{
  shopt -s histappend cmdhist lithist

  # If shell is interactive, disable START/STOP output control.
  # This allows Ctrl-S to trigger i-search.
  if [[ $- = *i* ]]; then
    # -ixon : Disable START/STOP output control.
    # This allows Ctrl-S to trigger i-search.
    stty -ixon
  fi

  unset -v MAILCHECK
}

# ::::::::: History ::::::::::::::::::::::::::
{
  HISTTIMEFORMAT='%F %T '
  HISTCONTROL=erasedups:ignorespace
  HISTSIZE=10000
  HISTFILESIZE=20000
  HISTIGNORE='jobs:[fb]g:history:gst:tls:fgg'
}

# ::::::::: Completion :::::::::::::::::::::::

# Bash completion
if [ -r ~/.nix-profile/share/bash-completion/bash_completion ]; then
  . ~/.nix-profile/share/bash-completion/bash_completion
  __load_completion tmux # alias (t) doesn't trigger dynamic completion loading
fi
for f in ~/.nix-profile/etc/bash_completion.d/*; do
  [ -r "$f" ] && . "$f"
done

# Display all 2856 possibilities? Um, no thanks
shopt -s no_empty_cmd_completion

# Kubectl shell completion
[ -r ~/.kube/completion.bash.inc ] && . ~/.kube/completion.bash.inc

# minikube shell completion
[ -r ~/.minikube/completion.bash.inc ] && . ~/.minikube/completion.bash.inc

eval "$(stack --bash-completion-script stack 2>/dev/null)"

# lpass
LPASS_AGENT_TIMEOUT=$(( 12 * 60 * 60 ))

FZF_DEFAULT_COMMAND="fd -t file -E GTAGS -E GRTAGS -E GPATH"
export FZF_DEFAULT_OPTS
FZF_DEFAULT_OPTS="\
    --prompt='• '
    --history=$HOME/.fzf-history
    --bind=ctrl-p:up
    --bind=ctrl-n:down
    --bind=alt-p:previous-history
    --bind=alt-n:next-history
    --exact
    --color=fg+:#c4d5e5
    --color=bg+:#222222
    --color=hl+:#f8bb39
    --color=hl:#26a6a6
    --color=info:#48778b
    --color=marker:#bbe068
    --color=pointer:#222222
    --color=prompt:#b8e068
    --color=spinner:#181818"
FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
FZF_CTRL_T_OPTS="\
    --preview-window=hidden
    --bind='?:toggle-preview'
    --preview='[[ \$(file --mime {}) =~ binary ]] &&
                   echo {} is a binary file ||
                   (highlight -O ansi -l {} ||
                    cat {}) 2> /dev/null | head -500'"
FZF_TMUX=1

# rbenv
# export PATH="$HOME/.rbenv/bin:$PATH"
# export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
# if command -v rbenv > /dev/null; then eval "$(rbenv init -)"; fi
