#!/bin/sh

CC() {
  setxkbmap -option 'caps:none,shift:both_capslock,caps:ctrl_modifier'
  __caps_already_xcaped || xcape -e 'Caps_Lock=Escape'
}

__caps_already_xcaped() {
  pgrep --full \
        --exact \
        "xcape -e Caps_Lock Escape" \
        &>/dev/null
}

EE() {
  if [[ $(__get_key_theme) =~ Default ]]; then
    __set_key_theme "Emacs"
  else
    __set_key_theme "Default"
  fi
}

__get_key_theme() {
  gsettings get org.gnome.desktop.interface gtk-key-theme
}

__set_key_theme() {
  gsettings set org.gnome.desktop.interface gtk-key-theme $1
}
