#!/bin/sh

# ::::::::: Reload :::::::::::::::::::::::::::
alias SS=". ~/.bashrc"

# ::::::::: Git ::::::::::::::::::::::::::::::
alias gst="git status"
alias gpr="git log origin/master.. --reverse"
alias gpt="git log origin/master.. --reverse --pretty='[\`%h\`](https://github.com/Handybook/handybook/commit/%H) %s'"
alias gpp="git log origin/master.. --reverse -p"
alias gpc="git log origin/master.. -- | wc -l"

# ::::::::: Tmux  ::::::::::::::::::::::::::::
alias t='tmux'
alias tls='tmux ls'
complete -F _tmux t

# ::::::::: Ls :::::::::::::::::::::::::::::::
alias ls='ls --color=auto'
alias l='ls -alF'
alias la='ls -A'
alias l1='ls -1F'

alias grep='grep --color=auto'
