#!/usr/bin/env bash

# These changes take effect immediately and persist across logins.

gsettings set org.gnome.desktop.input-sources xkb-options \
  "['caps:ctrl_modifier', 'shift:both_capslock']"

gsettings set org.gnome.desktop.interface gtk-key-theme "Emacs"
gsettings set org.gnome.desktop.interface clock-format "12h"

gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.peripherals.touchpad click-method "fingers"

gsettings set org.gnome.desktop.peripherals.keyboard delay 200
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 30

gsettings set org.gnome.Terminal.Legacy.Settings default-show-menubar false
gsettings set org.gnome.Terminal.Legacy.Settings theme-variant "dark"

keybindings=Keybindings:/org/gnome/terminal/legacy/keybindings/

gsettings set org.gnome.Terminal.Legacy.${keybindings} copy '<Ctrl><Alt>c'
gsettings set org.gnome.Terminal.Legacy.${keybindings} paste '<Ctrl><Alt>v'

gsettings set org.gnome.Terminal.Legacy.${keybindings} new-window '<Ctrl><Alt>n'
gsettings set org.gnome.Terminal.Legacy.${keybindings} new-tab '<Ctrl><Alt>t'

gsettings set org.gnome.Terminal.Legacy.${keybindings} toggle-menubar '<Ctrl><Alt>b'
gsettings set org.gnome.Terminal.Legacy.${keybindings} full-screen '<Ctrl><Alt>Return'

gnome_terminal_profile() {
  local uuid=$(gsettings get org.gnome.Terminal.ProfilesList default)
  local schema='org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles'
  printf '%s:/:%s/' ${schema} ${uuid:1:-1}
}

gnome_terminal_set() {
  local key=$1 val=$2
  gsettings set "$(gnome_terminal_profile)" "$key" "$val"
}

gnome_terminal_list() {
  gsettings list-recursively "$(gnome_terminal_profile)"
}

set_colors_from_dynamic_scope() {
  local palette vars

  palette="['$c00', '$c01', '$c02', '$c03', '$c04', '$c05', '$c06', '$c07',
            '$c08', '$c09', '$c10', '$c11', '$c12', '$c13', '$c14', '$c15']"

  vars=(
    background_color
    foreground_color
    cursor_background_color
    cursor_foreground_color
    cursor_colors_set
    highlight_background_color
    highlight_foreground_color
    bold_color
    font
    use_system_font
    palette
  )

  for var in c{00..15} ${vars[@]}; do
    [ -n "${!var:-}" ] || exit -1
  done

  for var in ${vars[@]}; do
    gnome_terminal_set ${var//_/-} "${!var}"
  done
}

reset_colors() {
  local background_color='#000000' \
        foreground_color='#00FF00' \
        cursor_background_color='#000000' \
        cursor_foreground_color='#ffffff' \
        cursor_colors_set='false' \
        highlight_background_color='#000000' \
        highlight_foreground_color='#ffffff' \
        bold_color='#000000' \
        font='Monospace 11' \
        use_system_font='true'

  local c00 c01 c02 c03 c04 c05 c06 c07 \
        c08 c09 c10 c11 c12 c13 c14 c15

  # c00='#000000'
  # c01='#cd0000'
  # c02='#00cd00'
  # c03='#cdcd00'
  # c04='#0000ee'
  # c05='#cd00cd'
  # c06='#00cdcd'
  # c07='#e5e5e5'
  # c08='#7f7f7f'
  # c09='#ff0000'
  # c10='#00ff00'
  # c11='#ffff00'
  # c12='#9292ff'
  # c13='#ff00ff'
  # c14='#00ffff'
  # c15='#ffffff'

  # Normal colors
  c00='#2E2E34343636' # black
  c01='#CCCC00000000' # red
  c02='#4E4E9A9A0606' # green
  c03='#C4C4A0A00000' # yellow
  c04='#34346565A4A4' # blue
  c05='#757550507B7B' # magenta
  c06='#060698209A9A' # cyan
  c07='#D3D3D7D7CFCF' # white

  # Bright colors
  c08='#555557575353' # black
  c09='#EFEF29292929' # red
  c10='#8A8AE2E23434' # green
  c11='#FCFCE9E94F4F' # yellow
  c12='#72729F9FCFCF' # blue
  c13='#ADAD7F7FA8A8' # magenta
  c14='#3434E2E2E2E2' # cyan
  c15='#EEEEEEEEECEC' # white

  set_colors_from_dynamic_scope
}

night_colors() {
  local background_color='#14171d' \
        foreground_color='#d5d8dc' \
        cursor_background_color='#d2d8e3' \
        cursor_foreground_color='#191e22' \
        cursor_colors_set='true' \
        highlight_background_color='#1c1f26' \
        highlight_foreground_color='#ffffff' \
        bold_color='#ffffff' \
        font='Source Code Pro 12' \
        use_system_font='false'

  local c00 c01 c02 c03 c04 c05 c06 c07 \
        c08 c09 c10 c11 c12 c13 c14 c15

  # Normal colors
  c00='#14171d' # black
  c01='#de4d3a' # red
  c02='#b8e068' # green
  c03='#ebcb8b' # yellow
  c04='#61b3c9' # blue
  c05='#617fa0' # magenta
  c06='#69d2e7' # cyan
  c07='#d5d8dc' # white

  # Bright colors
  c08='#303d4b' # black
  c09='#f4718c' # red
  c10='#d8e778' # green
  c11='#f8bb39' # yellow
  c12='#a1b3c9' # blue
  c13='#53769d' # magenta
  c14='#26a6a6' # cyan
  c15='#ffffff' # white

  set_colors_from_dynamic_scope
}

# Reference
# org.gnome.Terminal.Legacy.Profile audible-bell false
# org.gnome.Terminal.Legacy.Profile cursor-shape 'underline'
# org.gnome.Terminal.Legacy.Profile scroll-on-keystroke true
# org.gnome.Terminal.Legacy.Profile cursor-colors-set true
# org.gnome.Terminal.Legacy.Profile cjk-utf8-ambiguous-width 'narrow'
# org.gnome.Terminal.Legacy.Profile default-size-rows 24
# org.gnome.Terminal.Legacy.Profile encoding 'UTF-8'
# org.gnome.Terminal.Legacy.Profile use-theme-colors false
# org.gnome.Terminal.Legacy.Profile custom-command ''
# org.gnome.Terminal.Legacy.Profile visible-name 'linux'
# org.gnome.Terminal.Legacy.Profile login-shell false
# org.gnome.Terminal.Legacy.Profile exit-action 'close'
# org.gnome.Terminal.Legacy.Profile use-system-font false
# org.gnome.Terminal.Legacy.Profile rewrap-on-resize true
# org.gnome.Terminal.Legacy.Profile backspace-binding 'ascii-delete'
# org.gnome.Terminal.Legacy.Profile foreground-color 'rgb(206,219,224)'
# org.gnome.Terminal.Legacy.Profile bold-color-same-as-fg false
# org.gnome.Terminal.Legacy.Profile background-transparency-percent 50
# org.gnome.Terminal.Legacy.Profile cursor-blink-mode 'system'
# org.gnome.Terminal.Legacy.Profile default-show-menubar true
# org.gnome.Terminal.Legacy.Profile default-size-columns 80
# org.gnome.Terminal.Legacy.Profile background-color 'rgb(0,0,0)'
# org.gnome.Terminal.Legacy.Profile palette ['rgb(0,0,0)', 'rgb(205,0,0)', 'rgb(0,205,0)', 'rgb(205,205,0)', 'rgb(0,0,238)', 'rgb(205,0,205)', 'rgb(0,205,205)', 'rgb(229,229,229)', 'rgb(127,127,127)', 'rgb(255,0,0)', 'rgb(0,255,0)', 'rgb(255,255,0)', 'rgb(92,92,255)', 'rgb(255,0,255)', 'rgb(0,255,255)', 'rgb(255,255,255)']
# org.gnome.Terminal.Legacy.Profile cursor-foreground-color 'rgb(0,0,0)'
# org.gnome.Terminal.Legacy.Profile allow-bold true
# org.gnome.Terminal.Legacy.Profile use-theme-transparency true
# org.gnome.Terminal.Legacy.Profile highlight-foreground-color '#ffffff'
# org.gnome.Terminal.Legacy.Profile font 'Source Code Pro 11'
# org.gnome.Terminal.Legacy.Profile delete-binding 'delete-sequence'
# org.gnome.Terminal.Legacy.Profile scrollback-unlimited false
# org.gnome.Terminal.Legacy.Profile use-transparent-background false
# org.gnome.Terminal.Legacy.Profile cursor-background-color 'rgb(238,238,236)'
# org.gnome.Terminal.Legacy.Profile highlight-background-color '#000000'
# org.gnome.Terminal.Legacy.Profile scroll-on-output false
# org.gnome.Terminal.Legacy.Profile scrollbar-policy 'never'
# org.gnome.Terminal.Legacy.Profile use-custom-command false
# org.gnome.Terminal.Legacy.Profile bold-color 'rgb(255,255,255)'
# org.gnome.Terminal.Legacy.Profile highlight-colors-set false
# org.gnome.Terminal.Legacy.Profile scrollback-lines 10000
# org.gnome.Terminal.Legacy.Profile word-char-exceptions @ms nothing
