#!/usr/bin/env bash

export XDG_DATA_DIRS=$HOME/.nix-profile/share:$HOME/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/

# look into xmodmap

# configure caps lock behavior
xcape -e 'Caps_Lock=Escape' &

# activate drag lock
(
  dev_id=$( xinput --list | grep 'TouchPad' | grep -oP '(?<=\sid=)\d+(?=\s)' )
  props=$( xinput list-props ${dev_id} )
  prop_id=$( echo "$props" | grep -oP '(?<=Tapping Drag Lock Enabled \()\d+' )
  xinput set-prop $dev_id $prop_id 1
) &

# workaround until ibus is upgraded
#  https://github.com/jwilm/alacritty/issues/830
#  https://github.com/tomaka/winit/issues/277
#  https://github.com/ibus/ibus/issues/1907
ibus-daemon -xdr --panel disable

exec gnome-session
